[mypy]
plugins = pydantic.mypy

show_error_codes = true
warn_return_any = True
warn_unused_configs = true
disallow_untyped_calls = false
check_untyped_defs = true

exclude_gitignore=True

[mypy-tavily]
ignore_missing_imports = True

[mypy-tavily.*]
ignore_missing_imports = True

[mypy-ncatbot]
ignore_missing_imports = True

[mypy-ncatbot.*]
ignore_missing_imports = True
