executor.type = "uv"

# -------------------------------- Style & lint ---------------------------

[tasks._check]
help = "Check code style with ruff."
shell = "ruff check ."

[tasks._fix]
help = "Auto-fix lint issues with ruff."
shell = "ruff check . --fix"

[tasks._format]
help = "Format code with ruff."
shell = "ruff format ."

[tasks._lint]
help = "Run static type checks with mypy."
shell = "mypy ."

[tasks.style]
help = "Auto-fix and format the code using ruff."
sequence = ["_format", "_fix", "_format"]
ignore_fail = false

[tasks.lint]
help = "Check for style and type violations using ruff and mypy."
sequence = ["_check", "_lint"]
ignore_fail = false


# -------------------------------- Clean -------------------------------- 

[tasks._clean_pyc]
help = "Remove Python file artifacts"
shell = """
find . -name '*.pyc' -delete
find . -name '*.pyo' -delete
find . -name '*~' -delete
find . -type d -name '__pycache__' -exec rm -rf {} +
"""

[tasks._clean_build]
help = "Remove build artifacts"
shell = """
rm -rf build/ dist/ .eggs/
find . -name '*.egg-info' -exec rm -rf {} +
"""

[tasks._clean_test]
help = "Remove test and coverage artifacts"
shell = """
rm -rf tests/api/cassettes/ htmlcov/ .pytest_cache/
rm -f .coverage report.xml cov.xml
"""

[tasks._clean_lint]
help = "Remove lint artifacts"
shell = """
rm -rf .mypy_cache/ .ruff_cache/
"""

[tasks.clean]
help = "Remove all files generated by builds and tests."
sequence = ["_clean_build", "_clean_pyc", "_clean_test", "_clean_lint"]
ignore_fail = false


# -------------------------------- Test -------------------------------- 

[tasks._install_hooks]
help = "Install pre-commit hooks."
shell = "pre-commit install && pre-commit install-hooks"

[tasks._pre_commit]
help = "Run pre-commit checks."
shell = "pre-commit run --all-files --verbose"

[tasks.test]
help = "Run tests quickly using the default Python environment."
shell = "pytest tests"

[tasks.test-all]
help = "Run all tests."
sequence = ["style", "lint", "_install_hooks", "_pre_commit", "test"]
ignore_fail = false

[tasks.test-ci]
help = "Run CI tests."
sequence = ["_check", "_lint", "test"]
ignore_fail = false


# -------------------------------- Release -------------------------------- 

[tasks.build]
help = "Build source and wheel package."
shell = "uv build"

[tasks.tag]
help = "Create a new version tag."
shell = "semantic-release -c releaserc.toml -vv version"

[tasks.publish]
help = "Publish the package to PyPI."
shell = "uv publish -u admin -p ${PYPI_PASS} --index custom-repo"

[tasks.release]
help = "Build, tag, and publish the package."
sequence = ["build", "tag", "publish"]
ignore_fail = false
