[pytest]
log_format = %(asctime)s %(levelname)s %(message)s
log_date_format = %Y-%m-%d %H:%M:%S
testpaths = tests
python_files =
    test_*.py
    *_tests.py
    tests.py
addopts = 
    --maxfail=1 
    --capture=no 
    --tb=auto 
    --cov=src/snapbot
    --cov-report=term-missing:skip-covered 
    --cov-report=xml
    --junitxml=junit.xml 
    --cov-fail-under=0
    --cov-branch
    -vv
    -o junit_family=legacy
env =
    COVERAGE_PROCESS_START=.coveragerc

asyncio_mode = auto
